version: '3'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    expose: 
        - "8501"
    networks:
      - frontend_network
    environment:
      - VIRTUAL_HOST=hackyeah.lukaszsztukiewicz.com
      - VIRTUAL_PORT=8501
    container_name: streamlit

networks:
  frontend_network:
    driver: bridge